apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-api-prod
  namespace: argocd
spec:
  project: commerce
  source:
    repoURL: https://github.com/your-org/apps-gitops
    targetRevision: main
    path: services/user-api
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: icarus-prod    # <<< 필요 시 원하는 네임스페이스로 변경
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m