apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: commerce
  namespace: argocd
spec:
  description: "Commerce services"
  # Argo CD가 읽어올 수 있는 '소스 저장소' 화이트리스트
  # (배포 매니페스트 저장소는 반드시 포함)
  sourceRepos:
    - "https://github.com/JeongJin984/jeeson-menifest"
    # 필요시 코드/차트 참조 대비해 함께 허용 (여러 source를 쓸 경우)
    - "https://github.com/JeongJin984/jeeson-server.git"
    # 외부 Helm 리포를 쓰면 여기에 추가 (예: https://charts.bitnami.com/bitnami)

  # 배포 허용 대상 (클러스터/네임스페이스)
  destinations:
    - server: "https://kubernetes.default.svc"  # in-cluster
      namespace: "icarus-*"

  # (운영 정책에 맞춰 좁혀도 됩니다)
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"