# apps-gitops/projects/commerce/argo-project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jeeson-chat
  namespace: jeeson-chat
spec:
  description: "Commerce services"
  sourceRepos:
    - 'https://github.com/JeongJin984/jeeson-menifest.git'     # 환경 저장소
  destinations:
    - namespace: 'commerce-*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: readers
      description: Read-only
      policies:
        - p, proj:commerce:readers, applications, get, commerce/*, allow